apiVersion: v1
kind: Secret
metadata:
  name: openai-gpt-api-secret
type: Opaque
data:
  OPENAI_GPT_API_KEY: 
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-dalle-api-secret
type: Opaque
data:
  OPENAI_DALLE_API_KEY: